import { type Rarity } from "./priceHistory";

export interface BrandItem {
  slug: string;
  name: string;
  nameJp: string;
  brandSlug: string;
  brandName: string;
  category: string;
  releaseYear: number;
  origPrice: number;
  currentMarket: number;
  rarity: Rarity;
  description: string;
  searchKeyword: string;
  conditionPrices: { S: number; A: number; B: number; C: number };
  vintageBoost?: { era: string; multiplier: number }[];
  fakeTips?: string[];
}

export const BRAND_ITEMS: BrandItem[] = [
  // ── Levi's ──────────────────────────────────────────────
  {
    slug: "501",
    name: "Levi's 501",
    nameJp: "リーバイス 501",
    brandSlug: "levis",
    brandName: "Levi's",
    category: "デニム",
    releaseYear: 1873,
    origPrice: 12000,
    currentMarket: 8000,
    rarity: "common",
    description: "世界で最も有名なストレートデニム。年代によって価格差が大きく、60〜70年代の Big E は希少価値が高い。",
    searchKeyword: "リーバイス 501 ヴィンテージ",
    conditionPrices: { S: 12000, A: 8000, B: 5000, C: 2500 },
    vintageBoost: [
      { era: "1960s（Big E）", multiplier: 8.0 },
      { era: "1970s（シングルステッチ）", multiplier: 4.0 },
      { era: "1980s（USA製）", multiplier: 2.5 },
      { era: "1990s〜2000s", multiplier: 1.0 },
    ],
    fakeTips: ["ボタンフライの刻印「LEVI STRAUSS & CO」を確認", "赤タブの縫い方（両面 vs 片面）で年代判別", "股下の補強ステッチ（クロッチリベット）の有無"],
  },
  {
    slug: "505",
    name: "Levi's 505",
    nameJp: "リーバイス 505",
    brandSlug: "levis",
    brandName: "Levi's",
    category: "デニム",
    releaseYear: 1967,
    origPrice: 11000,
    currentMarket: 6500,
    rarity: "common",
    description: "501のジッパーフライ版。70〜80年代のUSA製が特に人気。ストレートシルエットで使いやすい。",
    searchKeyword: "リーバイス 505 USA製 ヴィンテージ",
    conditionPrices: { S: 10000, A: 6500, B: 4000, C: 2000 },
    vintageBoost: [
      { era: "1970s（USA製）", multiplier: 4.5 },
      { era: "1980s（USA製）", multiplier: 2.5 },
      { era: "1990s〜", multiplier: 1.0 },
    ],
  },
  {
    slug: "517",
    name: "Levi's 517",
    nameJp: "リーバイス 517",
    brandSlug: "levis",
    brandName: "Levi's",
    category: "デニム",
    releaseYear: 1971,
    origPrice: 11000,
    currentMarket: 9000,
    rarity: "uncommon",
    description: "ブーツカット・フレアシルエット。70年代を象徴するシルエットで、ヴィンテージ需要が高い。",
    searchKeyword: "リーバイス 517 ブーツカット ヴィンテージ",
    conditionPrices: { S: 14000, A: 9000, B: 6000, C: 3000 },
    vintageBoost: [
      { era: "1970s（フレア全盛期）", multiplier: 5.0 },
      { era: "1980s", multiplier: 2.0 },
    ],
  },
  {
    slug: "trucker-jacket",
    name: "Levi's トラッカージャケット",
    nameJp: "リーバイス トラッカージャケット",
    brandSlug: "levis",
    brandName: "Levi's",
    category: "ジャケット",
    releaseYear: 1962,
    origPrice: 18000,
    currentMarket: 12000,
    rarity: "uncommon",
    description: "Gジャンの代名詞。3rd（70〜80s）が最も人気。デニム素材のほかホワイト・ブラックも定番。",
    searchKeyword: "リーバイス Gジャン トラッカージャケット ヴィンテージ",
    conditionPrices: { S: 20000, A: 12000, B: 7000, C: 3500 },
    vintageBoost: [
      { era: "1960s（1st/2nd）", multiplier: 10.0 },
      { era: "1970〜80s（3rd）", multiplier: 3.0 },
      { era: "1990s〜", multiplier: 1.0 },
    ],
    fakeTips: ["ライニング（裏地）の織りネームを確認", "フロントボタン上部の横向き刻印", "ポケットフラップのステッチパターン"],
  },

  // ── Champion ────────────────────────────────────────────
  {
    slug: "reverse-weave",
    name: "Champion リバースウィーブ",
    nameJp: "チャンピオン リバースウィーブ",
    brandSlug: "champion",
    brandName: "Champion",
    category: "パーカー",
    releaseYear: 1952,
    origPrice: 8000,
    currentMarket: 15000,
    rarity: "uncommon",
    description: "横方向に編まれた縮みにくい生地が特徴。60〜80年代のUSA製タグが最高峰。ランタグ・バータグなど年代識別が奥深い。",
    searchKeyword: "チャンピオン リバースウィーブ ヴィンテージ",
    conditionPrices: { S: 22000, A: 15000, B: 9000, C: 4500 },
    vintageBoost: [
      { era: "1960〜70s（ランタグ）", multiplier: 8.0 },
      { era: "1980s（バータグ）", multiplier: 3.5 },
      { era: "1990s（C以降）", multiplier: 1.5 },
    ],
    fakeTips: ["横編みによる縦ストライプの織り目を確認", "左袖のCロゴ刺繍（年代で位置が変わる）", "タグの縫い付け方と糸の色"],
  },
  {
    slug: "t1011",
    name: "Champion T1011",
    nameJp: "チャンピオン T1011",
    brandSlug: "champion",
    brandName: "Champion",
    category: "Tシャツ",
    releaseYear: 1970,
    origPrice: 4000,
    currentMarket: 6000,
    rarity: "common",
    description: "肉厚で丈夫なヘビーウェイトT。USA製（Made in USA）タグのものが特に人気で、洗いこまれたヴィンテージ感が魅力。",
    searchKeyword: "チャンピオン T1011 USA製 ヴィンテージ",
    conditionPrices: { S: 9000, A: 6000, B: 3500, C: 1500 },
    vintageBoost: [
      { era: "1980s USA製", multiplier: 4.0 },
      { era: "1990s USA製", multiplier: 2.0 },
    ],
  },
  {
    slug: "coach-jacket",
    name: "Champion コーチジャケット",
    nameJp: "チャンピオン コーチジャケット",
    brandSlug: "champion",
    brandName: "Champion",
    category: "ジャケット",
    releaseYear: 1980,
    origPrice: 7000,
    currentMarket: 9000,
    rarity: "uncommon",
    description: "ナイロン素材の軽量ジャケット。カレッジ・大学名入りのヴィンテージ版が高値。スポーティなスタイルの定番。",
    searchKeyword: "チャンピオン コーチジャケット ヴィンテージ 大学",
    conditionPrices: { S: 14000, A: 9000, B: 5500, C: 2500 },
  },

  // ── Supreme ──────────────────────────────────────────────
  {
    slug: "box-logo-tee",
    name: "Supreme Box Logo Tee",
    nameJp: "シュプリーム ボックスロゴ Tシャツ",
    brandSlug: "supreme",
    brandName: "Supreme",
    category: "Tシャツ",
    releaseYear: 1994,
    origPrice: 8000,
    currentMarket: 35000,
    rarity: "rare",
    description: "Supreme の象徴。シーズンごとにカラー展開が変わり、黒白赤が定番。2000年代初期の旧タグは特に高額。",
    searchKeyword: "Supreme ボックスロゴ Tシャツ",
    conditionPrices: { S: 50000, A: 35000, B: 20000, C: 10000 },
    vintageBoost: [
      { era: "1990s〜2000s初期（旧タグ）", multiplier: 5.0 },
      { era: "2010s", multiplier: 2.0 },
      { era: "2020s〜", multiplier: 1.0 },
    ],
    fakeTips: ["タグの縫い目（二重縫い vs 粗縫い）", "インクの発色と立体感（プリントの厚み）", "胸ポケットの有無・位置"],
  },
  {
    slug: "box-logo-hoodie",
    name: "Supreme Box Logo Hoodie",
    nameJp: "シュプリーム ボックスロゴ パーカー",
    brandSlug: "supreme",
    brandName: "Supreme",
    category: "パーカー",
    releaseYear: 1994,
    origPrice: 18000,
    currentMarket: 80000,
    rarity: "very_rare",
    description: "毎シーズン即完売の最重要アイテム。定価の4〜5倍以上が当たり前の超希少品。偽物が最も多く流通している。",
    searchKeyword: "Supreme ボックスロゴ パーカー",
    conditionPrices: { S: 120000, A: 80000, B: 50000, C: 25000 },
    vintageBoost: [
      { era: "2000s（初期）", multiplier: 4.0 },
      { era: "2010s", multiplier: 2.5 },
    ],
    fakeTips: ["ネック裏タグの縫い付け精度", "カンガルーポケットの縫製と生地の厚み", "ドローコードの素材（本物はコットン）"],
  },

  // ── Nike ────────────────────────────────────────────────
  {
    slug: "air-force-1",
    name: "Nike Air Force 1",
    nameJp: "ナイキ エアフォース1",
    brandSlug: "nike",
    brandName: "Nike",
    category: "スニーカー",
    releaseYear: 1982,
    origPrice: 14000,
    currentMarket: 12000,
    rarity: "common",
    description: "バスケットボールシューズの定番。1982年のオリジナルや限定コラボは高値。ホワイト無地の通常版は手ごろな相場。",
    searchKeyword: "ナイキ エアフォース1 ヴィンテージ",
    conditionPrices: { S: 18000, A: 12000, B: 7000, C: 3000 },
    vintageBoost: [
      { era: "1982〜1986（オリジナル）", multiplier: 15.0 },
      { era: "1990s 復刻", multiplier: 3.0 },
    ],
    fakeTips: ["アウトソールの Swoosh の刻印精度", "ミッドソールのエアバッグの形状", "インソールのロゴプリント（かすれ・ズレ）"],
  },
  {
    slug: "air-max-95",
    name: "Nike Air Max 95",
    nameJp: "ナイキ エアマックス95",
    brandSlug: "nike",
    brandName: "Nike",
    category: "スニーカー",
    releaseYear: 1995,
    origPrice: 16000,
    currentMarket: 22000,
    rarity: "uncommon",
    description: "人体の筋肉・骨格をモチーフにした革新的デザイン。OG（オリジナルカラー）はプレ値が続く。",
    searchKeyword: "ナイキ エアマックス95 OG",
    conditionPrices: { S: 35000, A: 22000, B: 12000, C: 6000 },
    vintageBoost: [
      { era: "1995〜1999（OG）", multiplier: 5.0 },
      { era: "2000s 復刻", multiplier: 1.5 },
    ],
    fakeTips: ["グラデーションの滑らかさ（偽物はムラがある）", "アウトソールのプレート素材と色", "ヒールのAIRロゴのクリアさ"],
  },
  {
    slug: "cortez",
    name: "Nike Cortez",
    nameJp: "ナイキ コルテッツ",
    brandSlug: "nike",
    brandName: "Nike",
    category: "スニーカー",
    releaseYear: 1972,
    origPrice: 10000,
    currentMarket: 9000,
    rarity: "common",
    description: "Nike最初期モデル。70〜80年代の Nylon 版やレザー版は希少。映画・ドラマへの登場も多く根強い人気。",
    searchKeyword: "ナイキ コルテッツ ヴィンテージ",
    conditionPrices: { S: 14000, A: 9000, B: 5000, C: 2500 },
    vintageBoost: [
      { era: "1970s〜80s（旧ロゴ）", multiplier: 6.0 },
      { era: "1990s", multiplier: 2.0 },
    ],
  },

  // ── Carhartt ─────────────────────────────────────────────
  {
    slug: "detroit-jacket",
    name: "Carhartt デトロイトジャケット",
    nameJp: "カーハート デトロイトジャケット",
    brandSlug: "carhartt",
    brandName: "Carhartt",
    category: "ジャケット",
    releaseYear: 1989,
    origPrice: 22000,
    currentMarket: 18000,
    rarity: "uncommon",
    description: "ダック素材のワーカーズジャケットの代表格。USA製の旧モデルは特に質が高く人気。キルティングライニングが暖かい。",
    searchKeyword: "カーハート デトロイトジャケット USA製",
    conditionPrices: { S: 28000, A: 18000, B: 11000, C: 5000 },
    vintageBoost: [
      { era: "1990s（USA製）", multiplier: 2.5 },
      { era: "2000s", multiplier: 1.0 },
    ],
    fakeTips: ["左胸ポケット上の織りネームの精度", "ダック生地の厚みと重さ（正規品は重い）", "ボタンの刻印「CARHARTT」の均一さ"],
  },
  {
    slug: "duck-painter-pants",
    name: "Carhartt ダックペインターパンツ",
    nameJp: "カーハート ダックペインターパンツ",
    brandSlug: "carhartt",
    brandName: "Carhartt",
    category: "パンツ",
    releaseYear: 1985,
    origPrice: 12000,
    currentMarket: 10000,
    rarity: "common",
    description: "ハンマーループ付きのワークパンツ。USA製の旧タグ・fade加工されたヴィンテージが人気。",
    searchKeyword: "カーハート ペインターパンツ ダック ヴィンテージ",
    conditionPrices: { S: 15000, A: 10000, B: 6000, C: 2500 },
    vintageBoost: [
      { era: "1990s USA製", multiplier: 2.5 },
    ],
  },

  // ── Ralph Lauren ─────────────────────────────────────────
  {
    slug: "polo-shirt-vintage",
    name: "Ralph Lauren ヴィンテージポロシャツ",
    nameJp: "ラルフローレン ヴィンテージポロシャツ",
    brandSlug: "ralph-lauren",
    brandName: "Ralph Lauren",
    category: "Tシャツ",
    releaseYear: 1972,
    origPrice: 9000,
    currentMarket: 7000,
    rarity: "common",
    description: "80〜90年代のUSA製・RL社製ビッグポロが人気。刺繍の立体感と生地の厚みが現行品と異なる。",
    searchKeyword: "ラルフローレン ポロシャツ ヴィンテージ USA製",
    conditionPrices: { S: 12000, A: 7000, B: 4000, C: 1500 },
    vintageBoost: [
      { era: "1980s（USA製 ビッグポニー）", multiplier: 4.0 },
      { era: "1990s USA製", multiplier: 2.0 },
    ],
    fakeTips: ["ポロプレイヤー刺繍の糸の密度と立体感", "ボタンの素材（本物は天然素材・重め）", "タグの縫い付け方と文字フォント"],
  },
  {
    slug: "bear-knit",
    name: "Ralph Lauren ベアニット",
    nameJp: "ラルフローレン ベアニット",
    brandSlug: "ralph-lauren",
    brandName: "Ralph Lauren",
    category: "ニット",
    releaseYear: 1991,
    origPrice: 30000,
    currentMarket: 55000,
    rarity: "rare",
    description: "ポロベアがスキーウェアを着た人気ニット。特に90年代のRLX・Hand Knit版は10万円超えも。",
    searchKeyword: "ラルフローレン ベアニット ポロベア",
    conditionPrices: { S: 80000, A: 55000, B: 35000, C: 15000 },
    vintageBoost: [
      { era: "1991〜95（初期 Hand Knit）", multiplier: 3.0 },
      { era: "1996〜2000s", multiplier: 1.5 },
    ],
    fakeTips: ["ハンドニットの不均一な編み目（本物は少し不揃い）", "タグ「POLO RALPH LAUREN」の文字間隔", "ベア柄の色数と配色の精度"],
  },

  // ── Levi's 追加モデル ────────────────────────────────────
  {
    slug: "550",
    name: "Levi's 550",
    nameJp: "リーバイス 550",
    brandSlug: "levis",
    brandName: "Levi's",
    category: "デニム",
    releaseYear: 1985,
    origPrice: 11000,
    currentMarket: 5500,
    rarity: "common",
    description: "ゆったりとしたリラックスフィット。90年代USA製が人気で、ワイドシルエットブームで再評価。ブラックデニム版は特に需要高。",
    searchKeyword: "リーバイス 550 リラックスフィット ヴィンテージ",
    conditionPrices: { S: 9000, A: 5500, B: 3500, C: 1500 },
    vintageBoost: [
      { era: "1990s USA製", multiplier: 2.5 },
      { era: "1985〜89（初期）", multiplier: 3.0 },
    ],
  },
  {
    slug: "646",
    name: "Levi's 646",
    nameJp: "リーバイス 646",
    brandSlug: "levis",
    brandName: "Levi's",
    category: "デニム",
    releaseYear: 1969,
    origPrice: 11000,
    currentMarket: 18000,
    rarity: "rare",
    description: "70年代ヒッピーカルチャーを象徴するベルボトム・フレアデニム。517より裾が大きく開く極フレア。USA製70sが最高値。",
    searchKeyword: "リーバイス 646 ベルボトム フレア ヴィンテージ",
    conditionPrices: { S: 28000, A: 18000, B: 10000, C: 4000 },
    vintageBoost: [
      { era: "1969〜1975（Big E期）", multiplier: 8.0 },
      { era: "1976〜1982（Small e）", multiplier: 4.0 },
    ],
    fakeTips: ["裾幅が32cm以上あるか（本物はフレアが極端）", "股下の補強ステッチパターン", "サイズタグの年代フォント確認"],
  },
  {
    slug: "type1-jacket",
    name: "Levi's Type I ジャケット",
    nameJp: "リーバイス タイプ1ジャケット",
    brandSlug: "levis",
    brandName: "Levi's",
    category: "ジャケット",
    releaseYear: 1905,
    origPrice: 15000,
    currentMarket: 60000,
    rarity: "very_rare",
    description: "Gジャン最初期モデル。1905〜1953年に生産。シングルポケット・サスペンダーボタン付き。現存数が極めて少なく古着市場での最高峰の一つ。",
    searchKeyword: "リーバイス タイプ1 ファーストタイプ ヴィンテージ",
    conditionPrices: { S: 120000, A: 60000, B: 35000, C: 18000 },
    vintageBoost: [
      { era: "1905〜1936（初期）", multiplier: 20.0 },
      { era: "1937〜1953", multiplier: 8.0 },
    ],
    fakeTips: ["サスペンダーボタンの刻印「LS&CO SF CAL」", "ポケットがひとつ（左のみ）", "生地は極厚セルビッジ・コーンミルズ製"],
  },
  {
    slug: "sherpa-jacket",
    name: "Levi's シェルパトラッカー",
    nameJp: "リーバイス シェルパジャケット",
    brandSlug: "levis",
    brandName: "Levi's",
    category: "ジャケット",
    releaseYear: 1975,
    origPrice: 20000,
    currentMarket: 14000,
    rarity: "uncommon",
    description: "デニム×ボア裏地のコンビ。70〜80年代USA製は裏地のボアが高密度で暖かい。現行品より色落ちやクタリが味になりやすい。",
    searchKeyword: "リーバイス シェルパ ボア Gジャン ヴィンテージ",
    conditionPrices: { S: 22000, A: 14000, B: 8000, C: 3500 },
    vintageBoost: [
      { era: "1975〜85（USA製）", multiplier: 3.0 },
      { era: "1990s", multiplier: 1.5 },
    ],
  },

  // ── Barbour ──────────────────────────────────────────────
  {
    slug: "bedale",
    name: "Barbour Bedale",
    nameJp: "バブアー ビデイル",
    brandSlug: "barbour",
    brandName: "Barbour",
    category: "ジャケット",
    releaseYear: 1980,
    origPrice: 55000,
    currentMarket: 38000,
    rarity: "uncommon",
    description: "バブアーを代表するショート丈ワックスジャケット。乗馬用に設計。90年代英国製の旧タグが人気。定期的なリワックスで半永久的に使える。",
    searchKeyword: "バブアー ビデイル ワックスジャケット ヴィンテージ",
    conditionPrices: { S: 55000, A: 38000, B: 22000, C: 10000 },
    vintageBoost: [
      { era: "1980s（英国製 旧タグ）", multiplier: 2.5 },
      { era: "1990s（英国製）", multiplier: 1.8 },
      { era: "2000s〜", multiplier: 1.0 },
    ],
    fakeTips: ["左胸の織りネーム「BARBOUR」の縫い精度", "ジッパーはYKK製か確認", "ワックスの質感（本物はベタつきが均一）"],
  },
  {
    slug: "beaufort",
    name: "Barbour Beaufort",
    nameJp: "バブアー ボーフォート",
    brandSlug: "barbour",
    brandName: "Barbour",
    category: "ジャケット",
    releaseYear: 1968,
    origPrice: 65000,
    currentMarket: 48000,
    rarity: "uncommon",
    description: "ビデイルより長い丈でポケットが多いゲームジャケット。フィッシング・ハンティング用途。コーデュロイ襟が特徴的でクラシックな英国スタイル。",
    searchKeyword: "バブアー ボーフォート ワックスジャケット 英国製",
    conditionPrices: { S: 65000, A: 48000, B: 28000, C: 12000 },
    vintageBoost: [
      { era: "1970〜80s（旧タグ）", multiplier: 3.0 },
      { era: "1990s", multiplier: 1.8 },
    ],
    fakeTips: ["コーデュロイ襟の毛並みと色ムラ", "内ポケットのジッパー（YKK）", "袖のベルクロとボタンの質感"],
  },
  {
    slug: "border",
    name: "Barbour Border",
    nameJp: "バブアー ボーダー",
    brandSlug: "barbour",
    brandName: "Barbour",
    category: "ジャケット",
    releaseYear: 1978,
    origPrice: 50000,
    currentMarket: 32000,
    rarity: "uncommon",
    description: "ビデイルとボーフォートの中間丈。汎用性が高くタウンユース向け。ビンテージ市場では3ワラント（王室御用達3つ）付きの旧モデルが特に人気。",
    searchKeyword: "バブアー ボーダー ワックス ヴィンテージ 王室",
    conditionPrices: { S: 48000, A: 32000, B: 18000, C: 8000 },
    vintageBoost: [
      { era: "1980〜90s（3ワラント）", multiplier: 2.5 },
      { era: "2000s", multiplier: 1.2 },
    ],
    fakeTips: ["ワラント（王室御用達紋章）の刻印数と精度", "内タグに「BY APPOINTMENT TO」の記載確認", "ワックス表面のムラ・ひび割れの自然な経年感"],
  },
  {
    slug: "international",
    name: "Barbour International",
    nameJp: "バブアー インターナショナル",
    brandSlug: "barbour",
    brandName: "Barbour",
    category: "ジャケット",
    releaseYear: 1936,
    origPrice: 72000,
    currentMarket: 65000,
    rarity: "rare",
    description: "バイク・モータースポーツ向けの名作。スティーブ・マックイーンが着用したことで世界的に有名。オリジナルの旧タグは10万円超えも珍しくない。",
    searchKeyword: "バブアー インターナショナル スティーブマックイーン バイカー",
    conditionPrices: { S: 100000, A: 65000, B: 38000, C: 18000 },
    vintageBoost: [
      { era: "1936〜1960s（初期）", multiplier: 10.0 },
      { era: "1970〜80s", multiplier: 3.5 },
      { era: "1990s", multiplier: 1.8 },
    ],
    fakeTips: ["スナップボタンの刻印「BARBOUR」", "ハンドウォーマーポケットの位置と形状", "オイルドコットンの質感（固さとベタつきのバランス）"],
  },

  // ── Patagonia ────────────────────────────────────────────
  {
    slug: "synchilla-snap-t",
    name: "Patagonia Synchilla Snap-T",
    nameJp: "パタゴニア シンチラ スナップT",
    brandSlug: "patagonia",
    brandName: "Patagonia",
    category: "フリース",
    releaseYear: 1985,
    origPrice: 18000,
    currentMarket: 25000,
    rarity: "uncommon",
    description: "パタゴニアの看板アイテム。90年代製は配色が豊富でプリントデザインも多彩。「Made in USA」タグの初期型は希少。カラー・プリントによって価格差大。",
    searchKeyword: "パタゴニア シンチラ スナップT フリース ヴィンテージ",
    conditionPrices: { S: 38000, A: 25000, B: 14000, C: 6000 },
    vintageBoost: [
      { era: "1980s（USA製 初期）", multiplier: 6.0 },
      { era: "1990s（プリント柄）", multiplier: 3.0 },
      { era: "2000s〜", multiplier: 1.2 },
    ],
    fakeTips: ["タグのパタゴニアロゴ書体（年代で変遷）", "スナップボタンの刻印", "フリース素材のシンチラ特有のリップル感"],
  },
  {
    slug: "retro-x",
    name: "Patagonia レトロX",
    nameJp: "パタゴニア レトロXジャケット",
    brandSlug: "patagonia",
    brandName: "Patagonia",
    category: "フリース",
    releaseYear: 1994,
    origPrice: 42000,
    currentMarket: 55000,
    rarity: "rare",
    description: "ボア素材の高級フリース。初代（90s）の廃番カラーは6〜8万円台が当たり前。キッズサイズのヴィンテージも人気が高い。",
    searchKeyword: "パタゴニア レトロX ボア フリース ヴィンテージ",
    conditionPrices: { S: 80000, A: 55000, B: 30000, C: 15000 },
    vintageBoost: [
      { era: "1994〜1999（初期）", multiplier: 4.0 },
      { era: "2000s", multiplier: 2.0 },
    ],
    fakeTips: ["ボア素材の密度（本物は高密度で手触りが均一）", "ジッパープルのパタゴニアロゴ刻印", "ハンドポケットのジップ位置と形状"],
  },
  {
    slug: "baggies",
    name: "Patagonia バギーズショーツ",
    nameJp: "パタゴニア バギーズショーツ",
    brandSlug: "patagonia",
    brandName: "Patagonia",
    category: "パンツ",
    releaseYear: 1982,
    origPrice: 9000,
    currentMarket: 8000,
    rarity: "common",
    description: "軽量ナイロンのアウトドアショーツ。80〜90年代USA製の廃番カラー・プリント柄が高値。5インチ丈の旧モデルが人気。",
    searchKeyword: "パタゴニア バギーズ ショーツ ヴィンテージ",
    conditionPrices: { S: 13000, A: 8000, B: 5000, C: 2000 },
    vintageBoost: [
      { era: "1982〜1989（USA製）", multiplier: 5.0 },
      { era: "1990s（プリント柄）", multiplier: 2.5 },
    ],
  },
  {
    slug: "fleece-pullover",
    name: "Patagonia フリースプルオーバー",
    nameJp: "パタゴニア フリースプルオーバー",
    brandSlug: "patagonia",
    brandName: "Patagonia",
    category: "フリース",
    releaseYear: 1977,
    origPrice: 22000,
    currentMarket: 18000,
    rarity: "uncommon",
    description: "パタゴニア最初期のフリースアイテム。インターロックタグやグレー地タグの初期型は市場でも希少。ウインドシャーク（初期モデル名）表記があれば超希少。",
    searchKeyword: "パタゴニア フリース プルオーバー ヴィンテージ グレータグ",
    conditionPrices: { S: 28000, A: 18000, B: 10000, C: 4500 },
    vintageBoost: [
      { era: "1977〜1984（初期 USA製）", multiplier: 8.0 },
      { era: "1985〜1992", multiplier: 3.0 },
    ],
  },

  // ── The North Face ───────────────────────────────────────
  {
    slug: "nuptse",
    name: "The North Face ヌプシダウン",
    nameJp: "ザノースフェイス ヌプシダウンジャケット",
    brandSlug: "the-north-face",
    brandName: "The North Face",
    category: "ジャケット",
    releaseYear: 1992,
    origPrice: 35000,
    currentMarket: 45000,
    rarity: "uncommon",
    description: "バッフル（横縫い）構造のショートダウン。90年代USA製・廃番カラーは価格が2〜3倍。スノービーチコーデの定番としてストリートでも人気。",
    searchKeyword: "ノースフェイス ヌプシ ダウンジャケット ヴィンテージ",
    conditionPrices: { S: 65000, A: 45000, B: 25000, C: 12000 },
    vintageBoost: [
      { era: "1992〜1999（USA製）", multiplier: 4.0 },
      { era: "2000〜2009", multiplier: 1.8 },
      { era: "2010s〜", multiplier: 1.0 },
    ],
    fakeTips: ["ロゴワッペン（ハーフドーム）の縫い精度", "ダウンの充填量（本物は膨らみが均等）", "ジッパーはYKKかRIRI製"],
  },
  {
    slug: "mountain-jacket",
    name: "The North Face マウンテンジャケット",
    nameJp: "ザノースフェイス マウンテンジャケット",
    brandSlug: "the-north-face",
    brandName: "The North Face",
    category: "ジャケット",
    releaseYear: 1994,
    origPrice: 55000,
    currentMarket: 42000,
    rarity: "uncommon",
    description: "Gore-Tex使用のハードシェル。パープルラベル（Nanamica）コラボ版は別格の希少性。90s原型の廃番カラーも人気。実用性とデザイン性を両立。",
    searchKeyword: "ノースフェイス マウンテンジャケット ゴアテックス ヴィンテージ",
    conditionPrices: { S: 60000, A: 42000, B: 25000, C: 12000 },
    vintageBoost: [
      { era: "1994〜1999（USA製）", multiplier: 3.5 },
      { era: "2000s", multiplier: 1.5 },
    ],
    fakeTips: ["Gore-Texタグの正規ロゴ確認", "シームシーリングテープの均一さ", "裏地のフリース素材の質感"],
  },
  {
    slug: "denali",
    name: "The North Face デナリジャケット",
    nameJp: "ザノースフェイス デナリジャケット",
    brandSlug: "the-north-face",
    brandName: "The North Face",
    category: "ジャケット",
    releaseYear: 1997,
    origPrice: 30000,
    currentMarket: 20000,
    rarity: "common",
    description: "フリースジャケットの定番。ポーラーフリース素材と耐風性を両立。90s後期〜2000s初期の廃番カラーがヴィンテージ市場で人気。コーデュラ補強部分が特徴。",
    searchKeyword: "ノースフェイス デナリ フリースジャケット ヴィンテージ",
    conditionPrices: { S: 30000, A: 20000, B: 12000, C: 5000 },
    vintageBoost: [
      { era: "1997〜2005（廃番カラー）", multiplier: 3.0 },
      { era: "2006〜2015", multiplier: 1.5 },
    ],
    fakeTips: ["肩・ひじのコーデュラ生地の質感差", "ジップのプル形状（年代で変遷）", "タグの「ハーフドームロゴ」のラインの太さ"],
  },

  // ── Lee ───────────────────────────────────────────────────
  {
    slug: "101b",
    name: "Lee 101-B デニムジャケット",
    nameJp: "リー 101-B デニムジャケット",
    brandSlug: "lee",
    brandName: "Lee",
    category: "ジャケット",
    releaseYear: 1940,
    origPrice: 14000,
    currentMarket: 35000,
    rarity: "rare",
    description: "リーを代表するヴィンテージGジャン。プレスボタン・シンチバック付きの旧モデルは希少。ジェームズ・ディーン着用で伝説になった。USA製1950〜60sが最高峰。",
    searchKeyword: "リー 101B デニムジャケット ヴィンテージ USA製",
    conditionPrices: { S: 55000, A: 35000, B: 20000, C: 9000 },
    vintageBoost: [
      { era: "1940〜1959（初期）", multiplier: 15.0 },
      { era: "1960〜1970s", multiplier: 6.0 },
      { era: "1980s USA製", multiplier: 2.5 },
    ],
    fakeTips: ["フロントのストームフラップ（あり/なしで年代判別）", "プレスボタンのLEE刻印", "バックヨークのシンチバック金具の有無"],
  },
  {
    slug: "riders-jacket",
    name: "Lee ライダースジャケット",
    nameJp: "リー ライダースジャケット（91-B / 91-J）",
    brandSlug: "lee",
    brandName: "Lee",
    category: "ジャケット",
    releaseYear: 1929,
    origPrice: 12000,
    currentMarket: 18000,
    rarity: "rare",
    description: "世界初のウエスタンデニムジャケット。91-BやLBR（Lee Blanket Rider）など型番違いが複数存在。カウボーイ文化の象徴で、50〜60年代USA製は非常に高値。",
    searchKeyword: "リー ライダース ウエスタンジャケット ヴィンテージ 91B",
    conditionPrices: { S: 30000, A: 18000, B: 10000, C: 4500 },
    vintageBoost: [
      { era: "1929〜1959（初期）", multiplier: 12.0 },
      { era: "1960〜1970s", multiplier: 5.0 },
      { era: "1980s USA製", multiplier: 2.0 },
    ],
    fakeTips: ["バックヨークの刺繍（LEEロゴの有無）", "スナップボタンのLEE刻印", "生地はリジッドのセルビッジか確認"],
  },

  // ── Wrangler ─────────────────────────────────────────────
  {
    slug: "13mwz",
    name: "Wrangler 13MWZ",
    nameJp: "ラングラー 13MWZ",
    brandSlug: "wrangler",
    brandName: "Wrangler",
    category: "デニム",
    releaseYear: 1947,
    origPrice: 8000,
    currentMarket: 7000,
    rarity: "common",
    description: "カウボーイの定番デニム。PBR（プロロデオカウボーイ協会）公式認定ジーンズ。80〜90年代USA製がコスパ最高のヴィンテージとして人気。ブーツカットシルエット。",
    searchKeyword: "ラングラー 13MWZ デニム USA製 ヴィンテージ",
    conditionPrices: { S: 11000, A: 7000, B: 4500, C: 2000 },
    vintageBoost: [
      { era: "1947〜1969（初期）", multiplier: 10.0 },
      { era: "1970〜1980s USA製", multiplier: 3.0 },
      { era: "1990s USA製", multiplier: 1.5 },
    ],
    fakeTips: ["Wタグ（ウエスタンタグ）のロゴ形状", "バックポケットのW型ステッチの均一さ", "USA製なら腰部分の縫い目が二重縫い"],
  },
  {
    slug: "western-shirt",
    name: "Wrangler ウエスタンシャツ",
    nameJp: "ラングラー ウエスタンシャツ",
    brandSlug: "wrangler",
    brandName: "Wrangler",
    category: "シャツ",
    releaseYear: 1955,
    origPrice: 6000,
    currentMarket: 9000,
    rarity: "uncommon",
    description: "パールスナップボタンが特徴のウエスタンシャツ。70〜80年代の廃番プリント・刺繍柄が人気。現代のアメカジ・カントリースタイルにも合わせやすい。",
    searchKeyword: "ラングラー ウエスタンシャツ パールスナップ ヴィンテージ",
    conditionPrices: { S: 14000, A: 9000, B: 5500, C: 2500 },
    vintageBoost: [
      { era: "1955〜1969（初期刺繍）", multiplier: 6.0 },
      { era: "1970〜80s（USA製）", multiplier: 2.5 },
    ],
    fakeTips: ["パールスナップボタンのWランガー刻印", "ヨーク部分の刺繍の精度と針密度", "生地はコットン100%か（本物は厚手コットン）"],
  },

  // ── Stone Island ─────────────────────────────────────────
  {
    slug: "nylon-metal-jacket",
    name: "Stone Island ナイロンメタルジャケット",
    nameJp: "ストーンアイランド ナイロンメタルジャケット",
    brandSlug: "stone-island",
    brandName: "Stone Island",
    category: "ジャケット",
    releaseYear: 1994,
    origPrice: 80000,
    currentMarket: 120000,
    rarity: "very_rare",
    description: "メタリックコーティングのナイロン素材。90年代ヴィンテージは現行品の倍以上の相場になることも。",
    searchKeyword: "ストーンアイランド ナイロンメタル ヴィンテージ",
    conditionPrices: { S: 180000, A: 120000, B: 75000, C: 40000 },
    vintageBoost: [
      { era: "1990s（旧タグ）", multiplier: 2.5 },
      { era: "2000s", multiplier: 1.2 },
    ],
    fakeTips: ["左袖ワッペンの縫い目（本物は密で均一）", "コンパスロゴの刻印精度", "ジッパーの刻印ブランド名（YKKまたはRIRI）"],
  },
];

export function getItemsByBrand(brandSlug: string): BrandItem[] {
  return BRAND_ITEMS.filter((item) => item.brandSlug === brandSlug);
}

export function getItem(brandSlug: string, itemSlug: string): BrandItem | undefined {
  return BRAND_ITEMS.find((item) => item.brandSlug === brandSlug && item.slug === itemSlug);
}
