export type EventCategory = "蚤の市" | "古着市" | "骨董市" | "ヴィンテージフェア" | "フリマ";
export type EventArea = "東京" | "神奈川" | "大阪" | "京都" | "愛知" | "福岡" | "北九州" | "熊本" | "長崎" | "佐賀" | "大分" | "宮崎" | "鹿児島" | "北海道" | "宮城" | "広島";

export interface VintageEvent {
  id: number;
  name: string;
  area: EventArea;
  venue: string;
  category: EventCategory;
  schedule: string;
  nextDate?: string;
  url?: string;
  description: string;
  admission: string;
  tags: string[];
}

export const EVENTS: VintageEvent[] = [
  {
    id: 1,
    name: "大江戸骨董市",
    area: "東京",
    venue: "東京国際フォーラム",
    category: "骨董市",
    schedule: "毎月第1・第3日曜日",
    nextDate: "2026-08-02",
    url: "https://www.antique-market.jp",
    description: "日本最大級の骨董市。古着・ヴィンテージアクセサリーも多数出店。国内外から約250店舗が集まる。",
    admission: "無料",
    tags: ["骨董", "古着", "アクセサリー", "大規模"],
  },
  {
    id: 2,
    name: "世田谷ボロ市",
    area: "東京",
    venue: "世田谷代官屋敷周辺",
    category: "骨董市",
    schedule: "毎年12月15・16日、1月15・16日",
    nextDate: "2027-01-15",
    description: "450年以上の歴史を誇る年2回の市。ヴィンテージ衣類や古道具が並ぶ。",
    admission: "無料",
    tags: ["伝統", "骨董", "年2回", "屋外"],
  },
  {
    id: 3,
    name: "東京蚤の市",
    area: "東京",
    venue: "東京オーヴァル京王閣（調布）",
    category: "蚤の市",
    schedule: "年2〜3回",
    nextDate: "2026-05-10",
    url: "https://tokyonominoichi.com",
    description: "手紙社主催。ヴィンテージ古着・雑貨・家具の専門店が集まる人気イベント。",
    admission: "1,000円",
    tags: ["ヴィンテージ", "古着", "雑貨", "人気"],
  },
  {
    id: 4,
    name: "北欧市",
    area: "東京",
    venue: "東京オーヴァル京王閣（調布）",
    category: "蚤の市",
    schedule: "年1〜2回",
    nextDate: "2026-06-07",
    url: "https://tokyonominoichi.com",
    description: "手紙社主催。北欧ヴィンテージ食器・雑貨と古着が融合したマーケット。",
    admission: "1,000円",
    tags: ["北欧", "ヴィンテージ", "雑貨"],
  },
  {
    id: 5,
    name: "代官山蚤の市",
    area: "東京",
    venue: "代官山ヒルサイドテラス",
    category: "蚤の市",
    schedule: "年数回",
    nextDate: "2026-05-17",
    description: "おしゃれな代官山で開催。古着・ヴィンテージ・アート作品など多彩な出店。",
    admission: "無料",
    tags: ["代官山", "古着", "アート"],
  },
  {
    id: 6,
    name: "下北沢古着祭り",
    area: "東京",
    venue: "下北沢駅周辺各店",
    category: "古着市",
    schedule: "年2〜3回",
    nextDate: "2026-05-24",
    url: "https://shimokitazawa-vintage.jp",
    description: "古着の聖地・下北沢の各店舗が一斉セールを行う祭典。掘り出し物が豊富。",
    admission: "無料",
    tags: ["下北沢", "古着", "セール", "大規模"],
  },
  {
    id: 7,
    name: "東京フリマ（夢の島）",
    area: "東京",
    venue: "夢の島公園",
    category: "フリマ",
    schedule: "毎月第2・第4土曜日",
    nextDate: "2026-08-08",
    description: "都内最大級のフリーマーケット。古着・雑貨・ブランド品まで幅広く出品。",
    admission: "無料（出店者は有料）",
    tags: ["フリマ", "大規模", "ブランド品"],
  },
  {
    id: 8,
    name: "RAGSTOCK MARKET",
    area: "東京",
    venue: "代々木公園イベント広場",
    category: "古着市",
    schedule: "年2〜3回",
    nextDate: "2026-06-14",
    description: "アメリカ古着・ユーロ古着の専門バイヤーが集結するアウトドアマーケット。",
    admission: "無料",
    tags: ["アメリカ古着", "ユーロ古着", "屋外"],
  },
  {
    id: 9,
    name: "ヴィンテージマーケット原宿",
    area: "東京",
    venue: "ラフォーレ原宿",
    category: "ヴィンテージフェア",
    schedule: "年2回（春・秋）",
    nextDate: "2026-09-13",
    description: "ラフォーレ館内で開催。国内外のヴィンテージセレクトショップ30店以上が出展。",
    admission: "無料",
    tags: ["原宿", "ヴィンテージ", "ハイエンド"],
  },
  {
    id: 10,
    name: "横浜赤レンガ倉庫 古着市",
    area: "神奈川",
    venue: "横浜赤レンガ倉庫",
    category: "古着市",
    schedule: "年3〜4回",
    nextDate: "2026-05-30",
    description: "みなとみらいの名所で開催。古着・ヴィンテージを港の風景とともに楽しめる。",
    admission: "無料",
    tags: ["横浜", "港", "古着", "屋外"],
  },
  {
    id: 11,
    name: "鶴見のみの市",
    area: "神奈川",
    venue: "鶴見緑地公園",
    category: "フリマ",
    schedule: "毎月第4日曜日",
    nextDate: "2026-07-26",
    description: "神奈川最大規模のフリーマーケット。古着・雑貨の掘り出し物が豊富。",
    admission: "無料",
    tags: ["神奈川", "フリマ", "定期開催"],
  },
  {
    id: 12,
    name: "阪急うめだ ヴィンテージフェア",
    area: "大阪",
    venue: "阪急うめだ本店",
    category: "ヴィンテージフェア",
    schedule: "年2回（春・秋）",
    nextDate: "2026-09-20",
    description: "百貨店内で開催する上質なヴィンテージフェア。ラグジュアリーヴィンテージが中心。",
    admission: "無料",
    tags: ["大阪", "百貨店", "ラグジュアリー", "ヴィンテージ"],
  },
  {
    id: 13,
    name: "大阪古着蚤の市",
    area: "大阪",
    venue: "天王寺公園 てんしば",
    category: "蚤の市",
    schedule: "年4〜5回",
    nextDate: "2026-05-16",
    description: "関西最大級の古着特化型蚤の市。全国から古着ショップが大阪に集結。",
    admission: "無料",
    tags: ["大阪", "古着", "大規模", "関西"],
  },
  {
    id: 14,
    name: "中崎町 古道具市",
    area: "大阪",
    venue: "中崎町商店街周辺",
    category: "骨董市",
    schedule: "毎月第2土曜日",
    nextDate: "2026-08-08",
    description: "レトロな雰囲気の中崎町で開催。古着・古道具・ヴィンテージ小物が揃う。",
    admission: "無料",
    tags: ["中崎町", "レトロ", "古道具", "定期"],
  },
  {
    id: 15,
    name: "京都骨董祭",
    area: "京都",
    venue: "平安神宮前 岡崎公園",
    category: "骨董市",
    schedule: "年3回（春・夏・秋）",
    nextDate: "2026-05-22",
    description: "平安神宮前で開催される伝統的な骨董市。着物・帯・和雑貨が多く集まる。",
    admission: "無料",
    tags: ["京都", "骨董", "着物", "和雑貨"],
  },
  {
    id: 16,
    name: "京都蚤の市",
    area: "京都",
    venue: "梅小路公園",
    category: "蚤の市",
    schedule: "毎月第3土曜日",
    nextDate: "2026-08-15",
    url: "https://kyotonomarche.jp",
    description: "梅小路公園で毎月開催。古着・古道具・ハンドメイド作品が一堂に会す。",
    admission: "無料",
    tags: ["京都", "定期", "古着", "古道具"],
  },
  {
    id: 17,
    name: "名古屋ヴィンテージマーケット",
    area: "愛知",
    venue: "名古屋国際会議場",
    category: "ヴィンテージフェア",
    schedule: "年2回（春・秋）",
    nextDate: "2026-10-04",
    description: "東海最大級のヴィンテージイベント。古着・ヴィンテージ家具・レコードが充実。",
    admission: "500円",
    tags: ["名古屋", "ヴィンテージ", "東海", "大規模"],
  },
  {
    id: 18,
    name: "大須骨董市",
    area: "愛知",
    venue: "大須観音境内",
    category: "骨董市",
    schedule: "毎月18日・28日",
    nextDate: "2026-08-18",
    description: "大須観音の境内で開催される定期骨董市。古着・古道具・アンティーク品が並ぶ。",
    admission: "無料",
    tags: ["名古屋", "大須", "骨董", "定期"],
  },
  {
    id: 19,
    name: "福岡古着博",
    area: "福岡",
    venue: "マリンメッセ福岡",
    category: "古着市",
    schedule: "年1〜2回",
    nextDate: "2026-06-28",
    description: "九州最大の古着イベント。全国の古着ショップ・個人バイヤーが集結。",
    admission: "無料",
    tags: ["福岡", "古着", "九州", "大規模"],
  },
  {
    id: 20,
    name: "天神蚤の市",
    area: "福岡",
    venue: "天神中央公園",
    category: "蚤の市",
    schedule: "毎月第1日曜日",
    nextDate: "2026-08-02",
    description: "天神の中心部で開催。古着・雑貨・フード出店もあり週末のお出かけにぴったり。",
    admission: "無料",
    tags: ["福岡", "天神", "定期", "古着"],
  },
  {
    id: 21,
    name: "札幌蚤の市",
    area: "北海道",
    venue: "真駒内公園",
    category: "蚤の市",
    schedule: "年2回（初夏・初秋）",
    nextDate: "2026-06-20",
    description: "北海道最大の蚤の市。北欧ヴィンテージや道産の古着・工芸品が集まる。",
    admission: "無料",
    tags: ["札幌", "北欧", "ヴィンテージ", "屋外"],
  },
  {
    id: 22,
    name: "仙台古着まつり",
    area: "宮城",
    venue: "勾当台公園",
    category: "古着市",
    schedule: "年2回（春・秋）",
    nextDate: "2026-05-31",
    description: "東北最大の古着イベント。東北各地のショップが一堂に集まる。",
    admission: "無料",
    tags: ["仙台", "東北", "古着", "大規模"],
  },
  {
    id: 23,
    name: "広島古着マーケット",
    area: "広島",
    venue: "平和記念公園周辺",
    category: "古着市",
    schedule: "年3回",
    nextDate: "2026-07-19",
    description: "広島市中心部で開催される古着特化型マーケット。中国地方の古着ショップが集結。",
    admission: "無料",
    tags: ["広島", "古着", "中国地方"],
  },
  {
    id: 24,
    name: "下北沢レコード&古着フェア",
    area: "東京",
    venue: "下北沢BONUS TRACK",
    category: "古着市",
    schedule: "毎月第3土曜日",
    nextDate: "2026-08-15",
    description: "音楽と古着の街・下北沢で毎月開催。レコードと古着を同時に掘れるイベント。",
    admission: "無料",
    tags: ["下北沢", "レコード", "古着", "定期"],
  },
  {
    id: 25,
    name: "原宿ヴィンテージフリマ",
    area: "東京",
    venue: "神宮前公園",
    category: "ヴィンテージフェア",
    schedule: "毎月第2日曜日",
    nextDate: "2026-08-09",
    description: "原宿の中心で開催。海外バイヤーも多く訪れるヴィンテージ専門のマーケット。",
    admission: "無料",
    tags: ["原宿", "ヴィンテージ", "定期", "海外バイヤー"],
  },

  // ── 九州 ─────────────────────────────────────────────────
  {
    id: 26,
    name: "護国神社 蚤の市",
    area: "福岡",
    venue: "福岡縣護国神社境内",
    category: "蚤の市",
    schedule: "毎月（9月を除く）開催",
    nextDate: "2026-08-15",
    url: "https://g-nominoichi.com/",
    description: "約250店舗が出店する九州最大規模の蚤の市。古着・ヴィンテージアクセサリー・骨董品が揃う。西日本屈指の規模感で県外からの出店者も多い。",
    admission: "無料",
    tags: ["福岡", "護国神社", "九州最大", "定期", "骨董", "古着"],
  },
  {
    id: 27,
    name: "風の市場〜筥崎宮蚤の市",
    area: "福岡",
    venue: "筥崎宮参道",
    category: "蚤の市",
    schedule: "毎月第3日曜日（9月除く）",
    nextDate: "2026-08-16",
    description: "約220店舗が並ぶ筥崎宮参道の蚤の市。有田焼・伊万里焼などの陶磁器も多く、ヴィンテージ食器目当ての来場者も多い。西日本最大規模の一つ。",
    admission: "無料",
    tags: ["福岡", "筥崎宮", "陶器", "アンティーク", "定期"],
  },
  {
    id: 28,
    name: "福岡ヴィンテージマーケット",
    area: "福岡",
    venue: "博多港国際ターミナル3F",
    category: "ヴィンテージフェア",
    schedule: "年2回（冬・夏）",
    nextDate: "2026-12-19",
    url: "https://www.instagram.com/fukuoka_vintage_market/",
    description: "福岡・九州のヴィンテージショップ約70店が集結。アメリカ古着・ユーロ古着・ミリタリー・ワークウェアなどが揃う「九州最大のヴィンテージイベント」。",
    admission: "無料",
    tags: ["福岡", "博多港", "アメリカ古着", "ユーロ古着", "ミリタリー", "九州最大"],
  },
  {
    id: 29,
    name: "九州古着フェスティバル",
    area: "福岡",
    venue: "広川町産業展示館（八女郡）",
    category: "古着市",
    schedule: "年1〜2回（主に秋〜冬）",
    nextDate: "2026-11-28",
    url: "https://kurumefan.com/kyusyu-furugi-fes-hirokawa2025/",
    description: "九州全土の有名古着ショップが広川町に集結する古着特化型イベント。秋冬アイテムが揃い、特別価格での販売も。九州道広川ICより車3分。",
    admission: "無料",
    tags: ["福岡", "八女", "九州全土", "古着", "秋冬"],
  },
  {
    id: 30,
    name: "門司港 蚤の市",
    area: "北九州",
    venue: "門司港レトロ中央広場",
    category: "蚤の市",
    schedule: "年4〜6回（奇数月中心）",
    nextDate: "2026-05-30",
    url: "https://www.mojiko.info/kottou/",
    description: "レトロな街並みで有名な門司港で開催。大正・昭和のアンティーク・ヴィンテージ品が中心。港の景色を眺めながら掘り出し物探しが楽しめる。",
    admission: "無料",
    tags: ["北九州", "門司港", "レトロ", "アンティーク", "ヴィンテージ"],
  },
  {
    id: 31,
    name: "小倉古着ビンテージマーケット",
    area: "北九州",
    venue: "リバーウォーク北九州周辺",
    category: "ヴィンテージフェア",
    schedule: "年1〜2回",
    nextDate: "2026-11-20",
    url: "https://www.instagram.com/kokura_furugi_vintage_market/",
    description: "150店以上のヴィンテージ・アメカジ・アンティーク・キッズ古着店が集結する4日間イベント。フードトラックも出店し一日楽しめる。",
    admission: "無料",
    tags: ["北九州", "小倉", "アメカジ", "ヴィンテージ", "大規模"],
  },
  {
    id: 32,
    name: "九州蚤の市",
    area: "熊本",
    venue: "農業公園カントリーパーク（熊本市）",
    category: "蚤の市",
    schedule: "年2回（春・秋）",
    nextDate: "2026-04-25",
    url: "https://antique-leaves.com/",
    description: "熊本の広大な公園で開催される九州圏エリアの蚤の市。古着・古道具・クラフト品・フードが一堂に集まる家族連れにも人気のイベント。",
    admission: "無料",
    tags: ["熊本", "九州圏", "古道具", "クラフト", "家族向け"],
  },
  {
    id: 33,
    name: "長崎水辺の森 蚤の市",
    area: "長崎",
    venue: "水辺の森公園（長崎市）",
    category: "蚤の市",
    schedule: "年3〜4回",
    nextDate: "2026-06-07",
    description: "長崎港を望む水辺の森公園で開催。港町・長崎らしい異国情緒あふれるヴィンテージ品や古着が並ぶ。出島ワーフに隣接し観光客にも人気。",
    admission: "無料",
    tags: ["長崎", "水辺", "港", "異国情緒", "古着"],
  },
  {
    id: 34,
    name: "鹿児島アンティークマーケット",
    area: "鹿児島",
    venue: "かんまちぇあ（鹿児島市）",
    category: "骨董市",
    schedule: "年2回（春・秋）",
    nextDate: "2026-10-04",
    url: "https://kanmacheer.jp/",
    description: "九州全土からプロのディーラー約40店が集まるプロ向け骨董市。和骨董・ヨーロッパアンティーク・ヴィンテージ家具・古着まで幅広い品揃え。",
    admission: "無料",
    tags: ["鹿児島", "骨董", "プロディーラー", "九州", "アンティーク"],
  },
  {
    id: 35,
    name: "霧島フリーマーケット",
    area: "鹿児島",
    venue: "丸岡公園（霧島市横川町）",
    category: "フリマ",
    schedule: "毎月第2・第3日曜日",
    nextDate: "2026-08-09",
    description: "霧島市横川町の公園で毎月2回開催される地域フリマ。古着・雑貨が手ごろな価格で並ぶ。地元コミュニティの活気あるイベント。",
    admission: "無料",
    tags: ["鹿児島", "霧島", "フリマ", "定期", "地域"],
  },
  {
    id: 36,
    name: "大分古着&ヴィンテージポップアップ",
    area: "大分",
    venue: "アミュプラザおおいた（大分市）",
    category: "ヴィンテージフェア",
    schedule: "年2〜3回",
    nextDate: "2026-07-11",
    description: "大分駅直結のアミュプラザで開催されるポップアップイベント。九州内外の古着ショップが出店し、若い世代を中心に人気が高まっている。",
    admission: "無料",
    tags: ["大分", "ポップアップ", "ヴィンテージ", "駅ビル"],
  },
];

export const EVENT_AREAS = Array.from(new Set(EVENTS.map((e) => e.area))) as EventArea[];
export const EVENT_CATEGORIES = Array.from(new Set(EVENTS.map((e) => e.category))) as EventCategory[];
